### ISSUE TITLE
Feedback - Zoom Levels

### ISSUE THREAD

**Issue by six-shooter** [Perspective-Games/Tlatoani_Releases#3]
I am wondering if, and if so, where we could give player feedback.

I would love to be able to zoom in another level for example.

**Comment by Perspective-Games** [comment]
Hey there six-shooter:  Using the mouse-wheel to zoom should be included in the next version.  You can reach me at https://twitter.com/PerspectiveGam6 if you have other feedback, and there's also a Discord server:  https://discord.gg/GjnmU3vQ7p .
